import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { DashboardStore } from '../../core/state/dashboard.store';
import { readingSessionValidator } from './reading-session.validator';

@Component({ selector: 'folhea-reading', standalone: true, imports: [ReactiveFormsModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush, template: `
  <div class="form-page"><a routerLink="/app/inicio" class="back-link">← Início</a><p class="eyebrow">Mais uma página</p><h1>Registrar leitura</h1><p class="intro">Um registro rápido para manter seu ritmo visível.</p>@if (store.sessionsError(); as error) { <div class="alert alert-error" role="alert">{{ error }} A leitura precisa de conexão para sincronizar.</div> } @if (store.booksLoading() && store.books().length === 0) { <div class="loading surface" role="status"><span class="spinner"></span> Carregando livros…</div> } @else if (store.books().length === 0) { <section class="empty surface"><h2>Cadastre um livro primeiro.</h2><a routerLink="/app/livros/novo" class="button button-primary">Cadastrar livro</a></section> } @else { <form class="surface form-card" [formGroup]="form" (ngSubmit)="submit()" novalidate><label class="field">Livro<select formControlName="bookId" [attr.aria-invalid]="form.controls.bookId.invalid && form.controls.bookId.touched"><option value="" disabled>Escolha um livro</option>@for (book of store.books(); track book.id) { <option [value]="book.id">{{ book.title }}</option> }</select>@if (form.controls.bookId.invalid && form.controls.bookId.touched) { <span class="field-error">Escolha um livro.</span> }</label><div class="field-row"><label class="field">Páginas <span class="optional">opcional</span><input type="number" min="0" inputmode="numeric" formControlName="pages" placeholder="32" [attr.aria-invalid]="pages.invalid && pages.touched" />@if (pages.invalid && pages.touched) { <span class="field-error">Use zero ou um número positivo.</span> }</label><label class="field">Minutos <span class="optional">opcional</span><input type="number" min="0" inputmode="numeric" formControlName="minutes" placeholder="25" [attr.aria-invalid]="minutes.invalid && minutes.touched" />@if (minutes.invalid && minutes.touched) { <span class="field-error">Use zero ou um número positivo.</span> }</label></div><label class="field">Data<select formControlName="readingDate"><option [value]="today">Hoje, {{ displayToday }}</option><option [value]="yesterday">Ontem</option></select><span class="hint">A data usa o fuso horário do seu dispositivo.</span></label>@if (form.hasError('emptyReading') && form.touched) { <div class="alert alert-error" role="alert">Informe páginas ou minutos para registrar a sessão.</div> }<button type="submit" class="button button-primary">Registrar leitura <span aria-hidden="true">→</span></button></form> }
`, styles: [`:host{display:block}.form-page{max-width:34rem}.back-link{display:inline-block;margin-bottom:3rem;color:var(--forest-800);font-size:.8rem;font-weight:750}.form-page h1{margin:.65rem 0 .8rem;color:var(--forest-950);font-family:Georgia,serif;font-size:clamp(2.5rem,9vw,4.2rem);line-height:.98;letter-spacing:-.05em}.intro{margin:0 0 1.75rem;color:var(--muted);line-height:1.55}.form-card{display:grid;gap:1.15rem;padding:1.25rem}.field-row{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}.field .optional,.hint{color:var(--muted);font-size:.72rem;font-weight:500}.hint{font-weight:400}.form-card .button{margin-top:.4rem}.empty{display:grid;justify-items:center;gap:1rem;padding:2rem;text-align:center}.empty h2{margin:0;color:var(--forest-950);font-family:Georgia,serif;font-size:1.35rem}`] })
export class ReadingComponent {
  private readonly fb = inject(NonNullableFormBuilder); private readonly router = inject(Router); readonly store = inject(DashboardStore);
  readonly today = this.store.today(); readonly yesterday = this.previousDay(); readonly displayToday = new Intl.DateTimeFormat('pt-BR', { day: 'numeric', month: 'long' }).format(new Date());
  readonly form = this.fb.group({ bookId: ['', Validators.required], readingDate: [this.today, Validators.required], pages: [0, [Validators.min(0)]], minutes: [0, [Validators.min(0)]] }, { validators: readingSessionValidator });
  get pages() { return this.form.controls.pages; } get minutes() { return this.form.controls.minutes; }
  submit(): void { this.form.markAllAsTouched(); if (this.form.valid) { this.store.addSession({ bookId: this.form.controls.bookId.value, readingDate: this.form.controls.readingDate.value, pages: this.pages.value, minutes: this.minutes.value }); void this.router.navigate(['/app/ler/feedback'], { state: { pages: this.pages.value, minutes: this.minutes.value } }); } }
  private previousDay(): string { const date = new Date(); date.setDate(date.getDate() - 1); return new Intl.DateTimeFormat('en-CA').format(date); }
}
