import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { SeoService } from '../core/services/seo.service';

const pages: Record<string, { title: string; description: string; heading: string; intro: string; blocks: { title: string; text: string }[] }> = {
  'como-funciona': { title: 'Como funciona — Folhea', description: 'Entenda como o Folhea transforma leitura física em progresso visível.', heading: 'Seu hábito em três movimentos.', intro: 'Registrar uma leitura leva poucos segundos. O resto é deixar o progresso te acompanhar.', blocks: [{ title: '1. Leia do seu jeito', text: 'Escolha o livro que está na sua mesa e leia no seu ritmo, sem metas que pesem.' }, { title: '2. Registre o essencial', text: 'Informe páginas, minutos e a data. Páginas ou tempo: pelo menos um já basta.' }, { title: '3. Continue a história', text: 'Veja seu streak e suas métricas crescerem a cada sessão.' }] },
  recursos: { title: 'Recursos — Folhea', description: 'Streak, métricas e cards para acompanhar sua leitura.', heading: 'Tudo o que ajuda você a continuar.', intro: 'Uma experiência enxuta para quem quer enxergar o hábito, sem transformar leitura em planilha.', blocks: [{ title: 'Registro rápido', text: 'Um formulário simples, otimizado para celular e para voltar ao livro em menos de dez segundos.' }, { title: 'Progresso claro', text: 'Streak, páginas, tempo e livros finalizados aparecem onde você precisa deles.' }, { title: 'Cards de conquista', text: 'Transforme uma boa semana de leitura em um card que dá vontade de guardar.' }] },
  sobre: { title: 'Sobre — Folhea', description: 'Conheça o propósito do Folhea.', heading: 'Leitura física merece progresso visível.', intro: 'O Folhea nasceu para tornar o hábito de ler mais presente: menos controle, mais percepção.', blocks: [{ title: 'Nosso princípio', text: 'Cada página conta. O que importa é criar um registro que incentive o próximo dia.' }] },
  privacidade: { title: 'Privacidade — Folhea', description: 'Saiba como o Folhea trata seus dados.', heading: 'Privacidade é parte do produto.', intro: 'Seus registros de leitura pertencem a você. Esta página será atualizada com a política completa antes do lançamento.', blocks: [{ title: 'Dados mínimos', text: 'Coletamos apenas o necessário para autenticar sua conta e mostrar seu progresso.' }] },
  termos: { title: 'Termos — Folhea', description: 'Leia os termos de uso do Folhea.', heading: 'Termos de uso.', intro: 'Esta página será atualizada com os termos completos antes do lançamento público.', blocks: [{ title: 'Uso responsável', text: 'Ao utilizar o Folhea, você concorda em manter seus dados de acesso seguros e usar o serviço de forma legítima.' }] }
};

@Component({ selector: 'folhea-public-page', standalone: true, imports: [CommonModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush, template: `
  <header class="public-header container"><a class="brand" routerLink="/" aria-label="Folhea, início"><span class="brand-mark">F</span><span>folhea</span></a><a routerLink="/entrar" class="button button-secondary">Começar agora</a></header>
  <main class="public-page container"><p class="eyebrow">Folhea</p><h1>{{ page.heading }}</h1><p class="intro">{{ page.intro }}</p><section class="content-blocks"><article class="surface content-block" *ngFor="let block of page.blocks"><h2>{{ block.title }}</h2><p>{{ block.text }}</p></article></section><a routerLink="/" class="text-link">← Voltar para o início</a></main>
  <footer class="public-footer container"><span>© 2026 Folhea</span><span><a routerLink="/privacidade">Privacidade</a> · <a routerLink="/termos">Termos</a></span></footer>
`, styles: [`:host{display:block;min-height:100vh}.public-header{display:flex;align-items:center;justify-content:space-between;padding-block:1.2rem}.public-page{padding-block:4rem 6rem;max-width:58rem}.public-page h1{max-width:42rem;margin:.7rem 0 1.2rem;color:var(--forest-950);font-family:Georgia,serif;font-size:clamp(2.8rem,8vw,5.2rem);line-height:.98;letter-spacing:-.055em}.intro{max-width:35rem;color:var(--muted);font-size:1.15rem;line-height:1.65}.content-blocks{display:grid;gap:1rem;margin:3rem 0}.content-block{padding:1.5rem}.content-block h2{margin:0 0 .55rem;font-family:Georgia,serif;font-size:1.45rem}.content-block p{margin:0;color:var(--muted);line-height:1.65}.text-link{color:var(--forest-800);font-weight:750;text-decoration:underline;text-underline-offset:4px}`] })
export class PublicPageComponent {
  readonly page = pages[inject(ActivatedRoute).snapshot.data['page'] as string] ?? pages['sobre'];
  constructor() { inject(SeoService).update(this.page.title, this.page.description, `/${inject(ActivatedRoute).snapshot.data['page'] as string}`); }
}
