import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DashboardStore } from '../../core/state/dashboard.store';

@Component({ selector: 'folhea-books', standalone: true, imports: [RouterLink], changeDetection: ChangeDetectionStrategy.OnPush, template: `
  <div class="page-heading"><div><p class="eyebrow">Biblioteca</p><h1>Seus livros</h1></div><a routerLink="/app/livros/novo" class="button button-primary">+ Novo livro</a></div>
  @if (store.booksLoading() && store.books().length === 0) { <div class="loading surface" role="status"><span class="spinner"></span> Carregando seus livros…</div> } @else if (store.books().length === 0) { <section class="empty surface"><span class="empty-mark" aria-hidden="true">▤</span><h2>Sua biblioteca começa aqui.</h2><p>Cadastre o livro que está acompanhando agora.</p><a routerLink="/app/livros/novo" class="button button-primary">Cadastrar primeiro livro</a></section> } @else { <div class="book-list">@for (book of store.books(); track book.id) { <article class="book-row surface"><div class="book-thumb" aria-hidden="true">{{ book.title[0] }}</div><div class="book-info"><h2>{{ book.title }}</h2><p>{{ book.author || 'Autor não informado' }}</p><span class="status" [class.finished]="book.status === 'FINISHED'">{{ book.status === 'FINISHED' ? 'Finalizado' : 'Lendo agora' }}</span></div><a [routerLink]="['/app/livros', book.id]" class="row-arrow" [attr.aria-label]="'Abrir ' + book.title">→</a></article> }</div> }
`, styles: [`:host{display:grid;gap:1.5rem}.page-heading{display:flex;align-items:end;justify-content:space-between;gap:1rem}.page-heading h1{margin:.35rem 0 0;color:var(--forest-950);font-family:Georgia,serif;font-size:2.35rem;line-height:1}.empty{display:grid;justify-items:center;padding:3rem 1.5rem;text-align:center}.empty-mark{display:grid;place-items:center;width:4rem;height:4rem;border-radius:50%;color:var(--forest-800);background:var(--forest-100);font-size:1.6rem}.empty h2{margin:1.25rem 0 .4rem;font-family:Georgia,serif;font-size:1.55rem}.empty p{margin:0 0 1.5rem;color:var(--muted);font-size:.9rem}.book-list{display:grid;gap:.75rem}.book-row{display:flex;align-items:center;gap:1rem;padding:1rem}.book-thumb{display:grid;flex:none;place-items:center;width:3.5rem;height:4.5rem;border-radius:.4rem .65rem .65rem .4rem;color:var(--forest-950);background:var(--amber);font-family:Georgia,serif;font-size:1.7rem;box-shadow:inset .35rem 0 rgb(185 115 53 / 25%)}.book-info{min-width:0;flex:1}.book-info h2{margin:0 0 .2rem;overflow:hidden;color:var(--forest-950);font-family:Georgia,serif;font-size:1.15rem;text-overflow:ellipsis;white-space:nowrap}.book-info p{margin:0 0 .5rem;color:var(--muted);font-size:.78rem}.status{display:inline-block;border-radius:99px;padding:.25rem .5rem;color:var(--forest-800);background:var(--forest-100);font-size:.68rem;font-weight:750}.status.finished{color:#99672c;background:#fff0d5}.row-arrow{color:var(--forest-800);font-size:1.5rem}`] })
export class BooksComponent { readonly store = inject(DashboardStore); }
