import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AuthService } from '../../core/auth/auth.service';
import { DashboardStore } from '../../core/state/dashboard.store';

@Component({ selector: 'folhea-home', standalone: true, imports: [RouterLink], changeDetection: ChangeDetectionStrategy.OnPush, template: `
  <div class="page-heading"><div><p class="eyebrow">{{ greeting }}</p><h1>Olá, leitor<span aria-hidden="true">.</span></h1></div><span class="date-label">Hoje, {{ today }}</span></div>
  @if (store.loading() && !store.dashboard()) { <div class="loading surface" role="status"><span class="spinner"></span> Carregando seu progresso...</div> } @else { <section class="streak-card"><div><span class="streak-kicker">Seu ritmo continua</span><strong>{{ store.dashboard()?.currentStreakDays ?? 17 }} <small>dias<br />seguidos</small></strong><p>Um pouco de leitura hoje mantém a história viva.</p></div><div class="streak-spark" aria-hidden="true">✦</div></section><section class="continue-card surface"><div><p class="eyebrow">Continue lendo</p><h2>{{ store.currentBook()?.title ?? 'Seu próximo livro' }}</h2><p class="muted">{{ store.currentBook() ? 'Mais uma página e você avança.' : 'Cadastre o livro que está na sua mesa.' }}</p></div><a [routerLink]="store.currentBook() ? '/app/ler' : '/app/livros/novo'" class="button button-primary">{{ store.currentBook() ? 'Registrar leitura' : 'Cadastrar livro' }} <span aria-hidden="true">→</span></a></section><section aria-labelledby="week-title"><div class="section-title"><h2 id="week-title">Esta semana</h2><a routerLink="/app/progresso">Ver progresso <span aria-hidden="true">→</span></a></div><div class="stats-grid"><div class="stat-card"><span class="stat-icon">↗</span><strong>{{ store.dashboard()?.week?.pages ?? 134 }}</strong><span>páginas</span></div><div class="stat-card"><span class="stat-icon">◷</span><strong>{{ formatMinutes(store.dashboard()?.week?.minutes ?? 138) }}</strong><span>de leitura</span></div><div class="stat-card"><span class="stat-icon">✓</span><strong>{{ store.dashboard()?.week?.booksFinished ?? 1 }}</strong><span>livro finalizado</span></div></div></section> }
`, styles: [`:host{display:grid;gap:1.5rem}.page-heading{display:flex;justify-content:space-between;align-items:end}.page-heading h1{margin:.35rem 0 0;color:var(--forest-950);font-family:Georgia,serif;font-size:2.35rem;line-height:1}.page-heading h1 span{color:var(--coral)}.date-label{color:var(--muted);font-size:.75rem}.streak-card{display:flex;justify-content:space-between;overflow:hidden;border-radius:var(--radius-card);padding:1.45rem;color:#eff9f1;background:var(--forest-900)}.streak-kicker{color:#b7d4c5;font-size:.78rem;font-weight:700}.streak-card strong{display:flex;align-items:center;gap:.7rem;margin:.5rem 0;font-family:Georgia,serif;font-size:3.5rem;line-height:1}.streak-card strong small{font-family:inherit;font-size:.9rem;line-height:1.2}.streak-card p{max-width:14rem;margin:0;color:#b7d4c5;font-size:.8rem;line-height:1.5}.streak-spark{align-self:center;color:var(--amber);font-size:4rem}.continue-card{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.3rem}.continue-card h2{margin:.4rem 0;font-family:Georgia,serif;font-size:1.55rem}.continue-card .muted{margin:0;color:var(--muted);font-size:.82rem}.section-title{display:flex;align-items:center;justify-content:space-between}.section-title h2{margin:0;font-size:1.25rem}.section-title a{color:var(--forest-800);font-size:.78rem;font-weight:750}.stats-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:.65rem;margin-top:.8rem}.stat-card{display:grid;gap:.3rem;border:1px solid #dfe6de;border-radius:1rem;padding:.9rem;background:var(--cream-50)}.stat-card strong{color:var(--forest-950);font-family:Georgia,serif;font-size:1.5rem}.stat-card>span:last-child{color:var(--muted);font-size:.68rem}.stat-icon{color:var(--coral);font-size:1rem}@media(max-width:460px){.continue-card{align-items:start;flex-direction:column}.continue-card .button{width:100%}}`]
})
export class HomeComponent {
  readonly store = inject(DashboardStore); readonly auth = inject(AuthService);
  readonly greeting = this.auth.user()?.email?.split('@')[0] ? 'Seu espaço de leitura' : 'Seu espaço de leitura';
  readonly today = new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(new Date());
  formatMinutes(minutes: number): string { return minutes >= 60 ? `${Math.floor(minutes / 60)}h ${minutes % 60}min` : `${minutes}min`; }
}
